// ── Shared helpers ────────────────────────────────────────────────────────

function playerName(players, id) {
  if (!id || id === 'BYE') return 'BYE'
  return players.find(p => p.id === id)?.name ?? '???'
}

function divider(char = '─', len = 28) {
  return char.repeat(len)
}

function pad(str, len, dir = 'left') {
  const s = String(str ?? '')
  if (dir === 'left')  return s.padEnd(len)
  if (dir === 'right') return s.padStart(len)
  return s
}

function calcStandings(group, players, fixtures) {
  const gf = fixtures.filter(f => f.type === 'group' && f.groupId === group.id)
  const ids = group.playerIds.filter(id => players.some(p => p.id === id))
  const rows = ids.map(id => {
    const name = playerName(players, id)
    let P=0,W=0,D=0,L=0,GF=0,GA=0
    gf.forEach(f => {
      if (!f.played) return
      if (f.homeId===id){ P++;GF+=f.homeScore;GA+=f.awayScore; if(f.homeScore>f.awayScore)W++; else if(f.homeScore===f.awayScore)D++; else L++ }
      else if(f.awayId===id){ P++;GF+=f.awayScore;GA+=f.homeScore; if(f.awayScore>f.homeScore)W++; else if(f.awayScore===f.homeScore)D++; else L++ }
    })
    return { id, name, P, W, D, L, GF, GA, GD:GF-GA, Pts:W*3+D }
  })
  rows.sort((a,b)=>b.Pts-a.Pts||b.GD-a.GD||b.GF-a.GF||a.name.localeCompare(b.name))
  return rows
}

function getQualified(groups, players, fixtures, qualifierConfig) {
  const allData = groups.map(group => ({
    group, rows: calcStandings(group, players, fixtures),
    qualifiers: qualifierConfig?.perGroup?.[group.id] ?? 2,
  }))
  const direct = []
  allData.forEach(({ group, rows, qualifiers }) =>
    rows.slice(0, qualifiers).forEach((r,i) => direct.push({ ...r, groupName: group.name, rank: i+1 }))
  )
  const loserPool = []
  allData.forEach(({ group, rows, qualifiers }) =>
    rows.slice(qualifiers).forEach(r => loserPool.push({ ...r, groupName: group.name }))
  )
  loserPool.sort((a,b)=>b.Pts-a.Pts||b.GD-a.GD||b.GF-a.GF||a.name.localeCompare(b.name))
  const wildcards = loserPool.slice(0, qualifierConfig?.bestLosers ?? 0).map(r => ({ ...r, wildcard: true }))
  return { direct, wildcards, allData }
}

function getPairWinner(roundNum, pairIdx, fixtures, legs) {
  const pf = fixtures.filter(f => f.type==='knockout' && f.roundNum===roundNum && f.pairIdx===pairIdx)
  const leg1 = pf.find(f=>f.leg===1)
  if (!leg1) return null
  if (leg1.isBye) return leg1.homeId
  if (leg1.manualWinnerId) return leg1.manualWinnerId
  if (legs===1) {
    if (!leg1.played) return null
    if (leg1.homeScore>leg1.awayScore) return leg1.homeId
    if (leg1.awayScore>leg1.homeScore) return leg1.awayId
    return null
  } else {
    const leg2 = pf.find(f=>f.leg===2)
    if (!leg1.played||!leg2?.played) return null
    const gP1=(leg1.homeScore??0)+(leg2.awayScore??0)
    const gP2=(leg1.awayScore??0)+(leg2.homeScore??0)
    if (gP1>gP2) return leg1.homeId
    if (gP2>gP1) return leg1.awayId
    return null
  }
}

function getRoundLabel(roundNum, totalRounds) {
  const f = totalRounds - roundNum
  if (f===0) return 'FINAL'
  if (f===1) return 'SEMI FINALS'
  if (f===2) return 'QUARTER FINALS'
  if (f===3) return 'ROUND OF 16'
  return `ROUND ${roundNum}`
}

// ── Export functions ──────────────────────────────────────────────────────

export function exportGroupStandings(groups, players, fixtures, qualifierConfig) {
  if (!groups.length) return 'No groups set up yet.'
  const lines = []
  lines.push('📊 *GROUP STAGE STANDINGS*')
  lines.push(divider('═', 32))
  lines.push('')

  groups.forEach(group => {
    const rows = calcStandings(group, players, fixtures)
    const q    = qualifierConfig?.perGroup?.[group.id] ?? 2
    lines.push(`📋 *${group.name}*`)
    lines.push(divider())
    lines.push(`  ${pad('#',2)} ${pad('Player',12)} ${pad('P',2)} ${pad('W',2)} ${pad('D',2)} ${pad('L',2)} ${pad('Pts',3,'right')}`)
    lines.push(divider())
    rows.forEach((r, idx) => {
      const adv = idx < q ? '✅' : '  '
      const num = `${idx+1}.`
      lines.push(`${adv} ${pad(num,3)} ${pad(r.name,12)} ${pad(r.P,2)} ${pad(r.W,2)} ${pad(r.D,2)} ${pad(r.L,2)} ${pad(r.Pts,3,'right')}`)
    })
    lines.push(`  ✅ Top ${q} advance`)
    lines.push('')
  })

  lines.push(divider('═', 32))
  lines.push(`_Generated by EA26 Tournament Manager_`)
  return lines.join('\n')
}

export function exportResultsByRound(groups, players, fixtures, fixtureConfig) {
  const groupFix = fixtures.filter(f => f.type === 'group')
  if (!groupFix.length) return 'No fixtures generated yet.'

  const lines = []
  lines.push('⚽ *MATCH RESULTS — GROUP STAGE*')
  lines.push(divider('═', 32))

  // By round
  const byGroup = groups.map(group => ({
    group,
    all: groupFix.filter(f => f.groupId === group.id),
  }))
  const maxPerGroup = Math.max(...byGroup.map(g => g.all.length))

  for (let rIdx = 0; rIdx < maxPerGroup; rIdx++) {
    lines.push('')
    lines.push(`🔄 *ROUND ${rIdx+1}*`)
    lines.push(divider())
    byGroup.forEach(({ group, all }) => {
      const f = all[rIdx]
      if (!f) return
      const leg = fixtureConfig?.group === 2 ? ` (L${f.leg})` : ''
      const score = f.played
        ? `${f.homeScore} - ${f.awayScore}`
        : 'vs'
      const status = f.played ? '' : ' _(pending)_'
      lines.push(`  ${group.name}${leg}: ${playerName(players,f.homeId)} *${score}* ${playerName(players,f.awayId)}${status}`)
    })
  }

  lines.push('')
  lines.push(divider('═', 32))
  lines.push(`_Generated by EA26 Tournament Manager_`)
  return lines.join('\n')
}

export function exportQualifiers(groups, players, fixtures, qualifierConfig) {
  const { direct, wildcards } = getQualified(groups, players, fixtures, qualifierConfig)
  if (!direct.length) return 'No qualifiers yet.'

  const rankEmoji = ['🥇','🥈','🥉','4️⃣','5️⃣','6️⃣','7️⃣','8️⃣']
  const lines = []
  lines.push('🏆 *QUALIFIERS — KNOCKOUT STAGE*')
  lines.push(divider('═', 32))
  lines.push('')
  lines.push('*Direct Qualifiers*')
  lines.push(divider())

  // Group by group name
  const byGroup = {}
  direct.forEach(p => {
    if (!byGroup[p.groupName]) byGroup[p.groupName] = []
    byGroup[p.groupName].push(p)
  })
  Object.entries(byGroup).forEach(([grpName, ps]) => {
    const row = ps.map((p,i) => `${rankEmoji[i]||'✅'} ${p.name}`).join('  ')
    lines.push(`  ${grpName}: ${row}`)
  })

  if (wildcards.length) {
    lines.push('')
    lines.push('*🃏 Wildcards*')
    lines.push(divider())
    wildcards.forEach((p,i) => {
      lines.push(`  ${i+1}. ${p.name} (${p.groupName}) — ${p.Pts}pts`)
    })
  }

  lines.push('')
  lines.push(`  *Total advancing: ${direct.length + wildcards.length} players*`)
  lines.push(divider('═', 32))
  lines.push(`_Generated by EA26 Tournament Manager_`)
  return lines.join('\n')
}

export function exportKnockoutResults(players, fixtures, knockoutBracket, fixtureConfig) {
  if (!knockoutBracket?.locked) return 'Knockout bracket not started yet.'
  const { totalRounds } = knockoutBracket
  const koFix = fixtures.filter(f => f.type === 'knockout')
  if (!koFix.length) return 'No knockout fixtures yet.'

  const lines = []
  lines.push('🏆 *KNOCKOUT STAGE RESULTS*')
  lines.push(divider('═', 32))

  const rounds = [...new Set(koFix.map(f=>f.roundNum))].sort((a,b)=>a-b)

  rounds.forEach(rn => {
    const label = getRoundLabel(rn, totalRounds)
    const legs  = (() => {
      const f = totalRounds - rn
      if (f===0) return fixtureConfig?.final??1
      if (f===1) return fixtureConfig?.semi??1
      return fixtureConfig?.quarter??1
    })()
    const rf     = koFix.filter(f=>f.roundNum===rn)
    const pairs  = [...new Set(rf.map(f=>f.pairIdx))].sort((a,b)=>a-b)

    lines.push('')
    lines.push(`⚔️ *${label}*`)
    lines.push(divider())

    pairs.forEach(pi => {
      const pf   = rf.filter(f=>f.pairIdx===pi)
      const leg1 = pf.find(f=>f.leg===1)
      if (!leg1) return

      if (leg1.isBye) {
        lines.push(`  ${playerName(players,leg1.homeId)} — *BYE* (advances)`)
        return
      }

      const winner = getPairWinner(rn, pi, fixtures, legs)
      const wName  = winner ? playerName(players,winner) : null

      if (legs===1) {
        const score = leg1.played ? `${leg1.homeScore} - ${leg1.awayScore}` : 'vs _(pending)_'
        const note  = leg1.manualWinnerId ? ' *(ET/Pens)*' : ''
        const adv   = wName ? ` ✅ *${wName} advances*` : ''
        lines.push(`  ${playerName(players,leg1.homeId)} *${score}* ${playerName(players,leg1.awayId)}${note}${adv}`)
      } else {
        const leg2 = pf.find(f=>f.leg===2)
        const s1   = leg1.played ? `${leg1.homeScore}-${leg1.awayScore}` : '?-?'
        const s2   = leg2?.played ? `${leg2.homeScore}-${leg2.awayScore}` : '?-?'
        const agg1 = leg1.played&&leg2?.played ? (leg1.homeScore??0)+(leg2.awayScore??0) : '?'
        const agg2 = leg1.played&&leg2?.played ? (leg1.awayScore??0)+(leg2.homeScore??0) : '?'
        const note  = leg1.manualWinnerId ? ' *(ET/Pens)*' : ''
        const adv   = wName ? ` ✅ *${wName} advances*` : ''
        lines.push(`  ${playerName(players,leg1.homeId)} vs ${playerName(players,leg1.awayId)}`)
        lines.push(`    Leg 1: ${s1} | Leg 2: ${s2} | Agg: *${agg1}-${agg2}*${note}${adv}`)
      }
    })
  })

  lines.push('')
  lines.push(divider('═', 32))
  lines.push(`_Generated by EA26 Tournament Manager_`)
  return lines.join('\n')
}

export function exportLeaderboard(players, fixtures) {
  const played = fixtures.filter(f => f.played && !f.isBye)
  if (!played.length) return 'No results yet.'

  const board = players.map(player => {
    let MP=0,W=0,D=0,L=0,GF=0,Pts=0
    played.forEach(f => {
      const isHome=f.homeId===player.id, isAway=f.awayId===player.id
      if (!isHome&&!isAway) return
      MP++
      const mg=isHome?(f.homeScore??0):(f.awayScore??0)
      const tg=isHome?(f.awayScore??0):(f.homeScore??0)
      GF+=mg
      if (f.manualWinnerId) { if(f.manualWinnerId===player.id){W++;Pts+=3} else L++ }
      else { if(mg>tg){W++;Pts+=3} else if(mg===tg){D++;Pts+=1} else L++ }
    })
    return { ...player, MP, W, D, L, GF, Pts }
  }).filter(p=>p.MP>0).sort((a,b)=>b.Pts-a.Pts||b.GF-a.GF||a.name.localeCompare(b.name))

  const medals = ['🥇','🥈','🥉']
  const lines  = []
  lines.push('🏅 *OVERALL LEADERBOARD*')
  lines.push(divider('═', 32))
  lines.push(`  ${pad('#',3)} ${pad('Player',14)} ${pad('Pts',4,'right')} ${pad('GF',4,'right')} ${pad('W',3,'right')}`)
  lines.push(divider())

  board.forEach((p, idx) => {
    const rank = medals[idx] ?? `${String(idx+1).padStart(2)}.`
    lines.push(`  ${pad(rank,3)} ${pad(p.name,14)} ${pad(p.Pts,4,'right')} ${pad(p.GF,4,'right')} ${pad(p.W,3,'right')}`)
  })

  lines.push(divider('═', 32))
  lines.push(`_Generated by EA26 Tournament Manager_`)
  return lines.join('\n')
}

export function exportFixtures(groups, players, fixtures, fixtureConfig) {
  const groupFix = fixtures.filter(f => f.type === 'group')
  if (!groupFix.length) return 'No fixtures generated yet.'

  const lines = []
  lines.push('📅 *FIXTURES — GROUP STAGE*')
  lines.push(divider('═', 32))

  groups.forEach(group => {
    const all  = groupFix.filter(f => f.groupId === group.id)
    if (!all.length) return
    lines.push('')
    lines.push(`📋 *${group.name}*`)
    lines.push(divider())

    if (fixtureConfig?.group === 2) {
      const leg1 = all.filter(f=>f.leg===1)
      const leg2 = all.filter(f=>f.leg===2)
      lines.push('  🏠 *Leg 1*')
      leg1.forEach((f,i) => lines.push(`    ${i+1}. ${playerName(players,f.homeId)} vs ${playerName(players,f.awayId)}`))
      lines.push('  ✈️ *Leg 2*')
      leg2.forEach((f,i) => lines.push(`    ${i+1}. ${playerName(players,f.homeId)} vs ${playerName(players,f.awayId)}`))
    } else {
      all.forEach((f,i) => lines.push(`  ${i+1}. ${playerName(players,f.homeId)} vs ${playerName(players,f.awayId)}`))
    }
  })

  lines.push('')
  lines.push(divider('═', 32))
  lines.push(`_Generated by EA26 Tournament Manager_`)
  return lines.join('\n')
}